[package]
name = "xcq-api"
description = "API between XCQ host and guest program"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]

[features]
default = ["std"]
std = []
