[workspace]
resolver = "2"
members = [
    "poc/host",
    "poc/runtime",
    "poc/executor",
    "xcq-executor",
    "xcq-api",
    "xcq-extension",
    "xcq-extension-core",
    "xcq-extension-fungibles",
    "xcq-runtime-api",
    "xcq-types",
    "xcq-test-runner",
    "examples/example-fungibles",
    "examples/example-helloworld",
]
exclude = ["poc/guest", "vendor"]

[profile.release]
# runtime requires unwinding.
panic = "unwind"
opt-level = 3

[workspace.dependencies]
env_logger = { version = "0.11.3" }

polkavm = { path = "vendor/polkavm/crates/polkavm", default-features = false }
