[package]
name = "xcq-extension"
description = "Extension system for XCQ"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]

[features]
default = ["std"]
std = []
