[package]
name = "xcq-executor"
description = "XCQ program executor"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]

[features]
default = ["std"]
std = []
