[package]
name = "guest-swap-info"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
scale-info = { workspace = true }
parity-scale-codec = { workspace = true }
polkavm-derive = { workspace = true }
pvq-program = { workspace = true }
cfg-if = { workspace = true }
