[workspace]
members = ["sum-balance", "sum-balance-raw", "total-supply", "transparent-call"]
resolver = "2"


[workspace.dependencies]
polkavm-derive = { path = "../../vendor/polkavm/crates/polkavm-derive" }
xcq-api = { path = "../../xcq-api", default-features = false }
