[workspace]
members = ["pass-custom-type", "query-balance", "query-balance-fungibles"]
resolver = "2"


[workspace.dependencies]
polkavm-derive = { path = "../../vendor/polkavm/crates/polkavm-derive" }
