[workspace]
members = [
    "sum-balance",
    "sum-balance-percent",
    "total-supply",
    "transparent-call",
]
resolver = "2"


[workspace.dependencies]
polkavm-derive = { path = "../../vendor/polkavm/crates/polkavm-derive" }
pvq-api = { path = "../../pvq-api", default-features = false }
