[workspace]
members = ["query-balance", "query-balance-fungibles", "transparent-call"]
resolver = "2"


[workspace.dependencies]
polkavm-derive = { path = "../../vendor/polkavm/crates/polkavm-derive" }
