[package]
name = "sum-balance"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
parity-scale-codec = { workspace = true }
polkavm-derive = { workspace = true }
pvq-program = { workspace = true }
cfg-if = { workspace = true }

[features]
option_version_1 = []
option_version_2 = []
