name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: rust-src, rustfmt, clippy

      - name: Work around spurious network errors in curl 8.0
        run: |
          if rustc +stable --version --verbose | grep -q '^release: 1\.7[01]\.'; then
            echo CARGO_HTTP_MULTIPLEXING=false >> $GITHUB_ENV
          fi

      - uses: Swatinem/rust-cache@v2

      - name: Check format
        run: cargo fmt --all -- --check

      - name: Make dummy poc-guest-%.polkavm files
        run: make dummy-poc-guests

      - name: Cargo clippy
        run: SKIP_WASM_BUILD= cargo clippy -- -D warnings

      - name: Check no-std
        run: make check-wasm

      - name: Check std
        run: SKIP_WASM_BUILD= cargo check

  build-guest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: rustfmt, clippy

      - name: Work around spurious network errors in curl 8.0
        run: |
          if rustc +stable --version --verbose | grep -q '^release: 1\.7[01]\.'; then
            echo CARGO_HTTP_MULTIPLEXING=false >> $GITHUB_ENV
          fi

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: poc/guests -> poc/guests/target
          cache-all-crates: true

      - name: Install toolchain targeting RV32E
        run: |
          curl -sL https://github.com/paritytech/rustc-rv32e-toolchain/releases/download/v1.1.0/rust-rve-nightly-2024-01-05-x86_64-unknown-linux-gnu.tar.zst -o rv32e.tar.zst
          tar --zstd -xf rv32e.tar.zst
          mv rve-nightly ~/.rustup/toolchains/

      - name: Cargo clippy
        run: cd poc/guests; cargo clippy -- -D warnings

      - name: Install polkatool
        run: make polkatool
