name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: rust-src, rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Check format
        run: cargo fmt --all -- --check

      - name: Make dummy poc-guest files
        run: make dummy-guests

      - name: Check no-std
        run: make check-wasm

      - name: Clippy
        run: make clippy

      - name: Run tests
        run: make test

  build-guest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-src, rustfmt, clippy

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            guest-examples -> guest-examples/target
          cache-all-crates: true

      - name: Install polkatool
        run: make polkatool

      - name: Build guests
        run: make guests

